# Generated by Django 3.0.7 on 2020-07-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spacecrafts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=80)),
                ('manufacturer', models.CharField(max_length=80)),
                ('purpose', models.CharField(max_length=80)),
                ('orbit', models.CharField(max_length=80)),
                ('year', models.CharField(max_length=80)),
            ],
        ),
    ]
