# Generated by Django 3.0.7 on 2020-07-07 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReferenceBook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('spacecrafts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ReferenceBook.Spacecrafts')),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField(verbose_name='Текст статьи')),
            ],
        ),
    ]
