# Generated by Django 4.0.2 on 2022-02-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReferenceBook', '0002_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacecrafts',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
