# Generated by Django 4.0.2 on 2022-04-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReferenceBook', '0003_alter_spacecrafts_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
